### ISSUE TITLE
Most factual mode - gone

### ISSUE THREAD

**Issue by NSbuilder** [stanford-oval/WikiChat#12]
"Most factual" mode is gone with the new interface, impossible to use the gpt 4 version, despite Readme page on the website instructing the use of it.

**Comment by deter3** [comment]
make demo pipeline=early_combine do_refine=true engine=gpt-4 , is not working , the error is 

'''
Traceback (most recent call last):
  File "/root/anaconda3/envs/wikichat/lib/python3.8/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/root/anaconda3/envs/wikichat/lib/python3.8/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/root/anaconda3/envs/wikichat/lib/python3.8/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/anaconda3/envs/wikichat/lib/python3.8/site-packages/urllib3/connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
  File "/root/anaconda3/envs/wikichat/lib/python3.8/site-packages/urllib3/connectionpool.py", line 416, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/root/anaconda3/envs/wikichat/lib/python3.8/site-packages/urllib3/connection.py", line 244, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/root/anaconda3/envs/wikichat/lib/python3.8/http/client.py", line 1256, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/root/anaconda3/envs/wikichat/lib/python3.8/http/client.py", line 1302, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/root/anaconda3/envs/wikichat/lib/python3.8/http/client.py", line 1251, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/root/anaconda3/envs/wikichat/lib/python3.8/http/client.py", line 1011, in _send_output
    self.send(msg)
  File "/root/anaconda3/envs/wikichat/lib/python3.8/http/client.py", line 951, in send
    self.connect()
  File "/root/anaconda3/envs/wikichat/lib/python3.8/site-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
  File "/root/anaconda3/envs/wikichat/lib/python3.8/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f378834f730>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/anaconda3/envs/wikichat/lib/python3.8/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/root/anaconda3/envs/wikichat/lib/python3.8/site-packages/urllib3/connectionpool.py", line 799, in urlopen
    retries = retries.increment(
  File "/root/anaconda3/envs/wikichat/lib/python3.8/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /search (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f378834f730>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "chat_interactive.py", line 113, in <module>
    main(args)
  File "chat_interactive.py", line 49, in main
    new_dlg_turn = chatbot.generate_next_turn(
  File "/home/ubuntu/WikiChat/pipelines/chatbot.py", line 111, in generate_next_turn
    new_dlg_turn = self.early_combine_pipeline(
  File "/home/ubuntu/WikiChat/pipelines/chatbot.py", line 263, in early_combine_pipeline
    search_summary = search_summary.result()
  File "/root/anaconda3/envs/wikichat/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/root/anaconda3/envs/wikichat/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/root/anaconda3/envs/wikichat/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/ubuntu/WikiChat/pipelines/chatbot.py", line 481, in _search_and_summarize
    self._handle_search_prompt_output(
  File "/home/ubuntu/WikiChat/pipelines/chatbot.py", line 321, in _handle_search_prompt_output
    paragraphs, scores, titles = self._colbert_retrieve(
  File "/home/ubuntu/WikiChat/pipelines/chatbot.py", line 746, in _colbert_retrieve
    response = requests.get(
  File "/root/anaconda3/envs/wikichat/lib/python3.8/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/root/anaconda3/envs/wikichat/lib/python3.8/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/root/anaconda3/envs/wikichat/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/anaconda3/envs/wikichat/lib/python3.8/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/root/anaconda3/envs/wikichat/lib/python3.8/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /search (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f378834f730>: Failed to establish a new connection: [Errno 111] Connection refused'))
'''

**Comment by deter3** [comment]
> make demo pipeline=early_combine do_refine=true engine=gpt-4 , is not working , the error is
> 
> ```python
> Traceback (most recent call last):
>   File "/root/anaconda3/envs/wikichat/lib/python3.8/site-packages/urllib3/connection.py", line 174, in _new_conn
>     conn = connection.create_connection(
>   File "/root/anaconda3/envs/wikichat/lib/python3.8/site-packages/urllib3/util/connection.py", line 95, in create_connection
>     raise err
>   File "/root/anaconda3/envs/wikichat/lib/python3.8/site-packages/urllib3/util/connection.py", line 85, in create_connection
>     sock.connect(sa)
> ConnectionRefusedError: [Errno 111] Connection refused
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/root/anaconda3/envs/wikichat/lib/python3.8/site-packages/urllib3/connectionpool.py", line 715, in urlopen
>     httplib_response = self._make_request(
>   File "/root/anaconda3/envs/wikichat/lib/python3.8/site-packages/urllib3/connectionpool.py", line 416, in _make_request
>     conn.request(method, url, **httplib_request_kw)
>   File "/root/anaconda3/envs/wikichat/lib/python3.8/site-packages/urllib3/connection.py", line 244, in request
>     super(HTTPConnection, self).request(method, url, body=body, headers=headers)
>   File "/root/anaconda3/envs/wikichat/lib/python3.8/http/client.py", line 1256, in request
>     self._send_request(method, url, body, headers, encode_chunked)
>   File "/root/anaconda3/envs/wikichat/lib/python3.8/http/client.py", line 1302, in _send_request
>     self.endheaders(body, encode_chunked=encode_chunked)
>   File "/root/anaconda3/envs/wikichat/lib/python3.8/http/client.py", line 1251, in endheaders
>     self._send_output(message_body, encode_chunked=encode_chunked)
>   File "/root/anaconda3/envs/wikichat/lib/python3.8/http/client.py", line 1011, in _send_output
>     self.send(msg)
>   File "/root/anaconda3/envs/wikichat/lib/python3.8/http/client.py", line 951, in send
>     self.connect()
>   File "/root/anaconda3/envs/wikichat/lib/python3.8/site-packages/urllib3/connection.py", line 205, in connect
>     conn = self._new_conn()
>   File "/root/anaconda3/envs/wikichat/lib/python3.8/site-packages/urllib3/connection.py", line 186, in _new_conn
>     raise NewConnectionError(
> urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f378834f730>: Failed to establish a new connection: [Errno 111] Connection refused
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/root/anaconda3/envs/wikichat/lib/python3.8/site-packages/requests/adapters.py", line 486, in send
>     resp = conn.urlopen(
>   File "/root/anaconda3/envs/wikichat/lib/python3.8/site-packages/urllib3/connectionpool.py", line 799, in urlopen
>     retries = retries.increment(
>   File "/root/anaconda3/envs/wikichat/lib/python3.8/site-packages/urllib3/util/retry.py", line 592, in increment
>     raise MaxRetryError(_pool, url, error or ResponseError(cause))
> urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /search (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f378834f730>: Failed to establish a new connection: [Errno 111] Connection refused'))
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "chat_interactive.py", line 113, in <module>
>     main(args)
>   File "chat_interactive.py", line 49, in main
>     new_dlg_turn = chatbot.generate_next_turn(
>   File "/home/ubuntu/WikiChat/pipelines/chatbot.py", line 111, in generate_next_turn
>     new_dlg_turn = self.early_combine_pipeline(
>   File "/home/ubuntu/WikiChat/pipelines/chatbot.py", line 263, in early_combine_pipeline
>     search_summary = search_summary.result()
>   File "/root/anaconda3/envs/wikichat/lib/python3.8/concurrent/futures/_base.py", line 437, in result
>     return self.__get_result()
>   File "/root/anaconda3/envs/wikichat/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
>     raise self._exception
>   File "/root/anaconda3/envs/wikichat/lib/python3.8/concurrent/futures/thread.py", line 57, in run
>     result = self.fn(*self.args, **self.kwargs)
>   File "/home/ubuntu/WikiChat/pipelines/chatbot.py", line 481, in _search_and_summarize
>     self._handle_search_prompt_output(
>   File "/home/ubuntu/WikiChat/pipelines/chatbot.py", line 321, in _handle_search_prompt_output
>     paragraphs, scores, titles = self._colbert_retrieve(
>   File "/home/ubuntu/WikiChat/pipelines/chatbot.py", line 746, in _colbert_retrieve
>     response = requests.get(
>   File "/root/anaconda3/envs/wikichat/lib/python3.8/site-packages/requests/api.py", line 73, in get
>     return request("get", url, params=params, **kwargs)
>   File "/root/anaconda3/envs/wikichat/lib/python3.8/site-packages/requests/api.py", line 59, in request
>     return session.request(method=method, url=url, **kwargs)
>   File "/root/anaconda3/envs/wikichat/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
>     resp = self.send(prep, **send_kwargs)
>   File "/root/anaconda3/envs/wikichat/lib/python3.8/site-packages/requests/sessions.py", line 703, in send
>     r = adapter.send(request, **kwargs)
>   File "/root/anaconda3/envs/wikichat/lib/python3.8/site-packages/requests/adapters.py", line 519, in send
>     raise ConnectionError(e, request=request)
> requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /search (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f378834f730>: Failed to establish a new connection: [Errno 111] Connection refused'))
> ```

I found out i should use "make start-colbert-gunicorn wiki_date=11_06_2023 language=en" to start the colbert index in one terminal , and use "make demo pipeline=early_combine do_refine=true engine=gpt-4" in another terminal . then the interactive chat is working . 

I guess the readme may be add more clear instructions .

**Comment by s-jse** [comment]
> "Most factual" mode is gone with the new interface, impossible to use the gpt 4 version, despite Readme page on the website instructing the use of it. Quality is worse of course

I think the new front-end framework we are using has a bug, where it sometimes does not load all the components. Refreshing the page a few times seems to help for now. The page should look like this, and there is a "settings" button near the chatbox to select different versions.

![image](https://github.com/stanford-oval/WikiChat/assets/60150701/dea57fda-4c56-4a20-9591-022ec8ce06dc)

**Comment by NSbuilder** [comment]
> > "Most factual" mode is gone with the new interface, impossible to use the gpt 4 version, despite Readme page on the website instructing the use of it. Quality is worse of course
> 
> I think the new front-end framework we are using has a bug, where it sometimes does not load all the components. Refreshing the page a few times seems to help for now. The page should look like this, and there is a "settings" button near the chatbox to select different versions.
> 
> ![image](https://private-user-images.githubusercontent.com/60150701/300279890-dea57fda-4c56-4a20-9591-022ec8ce06dc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0NzkwNTQsIm5iZiI6MTcwNjQ3ODc1NCwicGF0aCI6Ii82MDE1MDcwMS8zMDAyNzk4OTAtZGVhNTdmZGEtNGM1Ni00YTIwLTk1OTEtMDIyZWM4Y2UwNmRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI4VDIxNTIzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAyZTJjNzhkMzNiNDk5NGQ3Y2YwYTAzZDk3Y2Q2ZTU4NzBmYjkyZDkxYzg1YmY2ZDEzM2M0Njc2YWMyOTliZDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4gUkHgwm_xHg_xr30uj3Ak1f9w7Ckw6nqNJHTWwpNNM)

Did not find the option anymore. Will wait for them to clarify

**Comment by deter3** [comment]
> > "Most factual" mode is gone with the new interface, impossible to use the gpt 4 version, despite Readme page on the website instructing the use of it. Quality is worse of course
> 
> I think the new front-end framework we are using has a bug, where it sometimes does not load all the components. Refreshing the page a few times seems to help for now. The page should look like this, and there is a "settings" button near the chatbox to select different versions.
> 
> ![image](https://private-user-images.githubusercontent.com/60150701/300279890-dea57fda-4c56-4a20-9591-022ec8ce06dc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1MDIzMjUsIm5iZiI6MTcwNjUwMjAyNSwicGF0aCI6Ii82MDE1MDcwMS8zMDAyNzk4OTAtZGVhNTdmZGEtNGM1Ni00YTIwLTk1OTEtMDIyZWM4Y2UwNmRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI5VDA0MjAyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRmNDM2MWUzYmY5Mzc4ZDc3NDYwODU4OGVlNGMxYTM3YjBiNjdjMTFlMDdkNjU2YmMzNDZhNGZkNDE3ODJjZDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0_lWcRLyPrSjkXT-rqK8JerSCzsO7biKXy3VD82E_VQ)

are u using the code from https://github.com/stanford-oval/ovalchat ? is there any specific instructions for wikichat to hook up the front end . thanks .

**Comment by s-jse** [comment]
> > > "Most factual" mode is gone with the new interface, impossible to use the gpt 4 version, despite Readme page on the website instructing the use of it. Quality is worse of course
> > 
> > 
> > I think the new front-end framework we are using has a bug, where it sometimes does not load all the components. Refreshing the page a few times seems to help for now. The page should look like this, and there is a "settings" button near the chatbox to select different versions.
> > ![image](https://private-user-images.githubusercontent.com/60150701/300279890-dea57fda-4c56-4a20-9591-022ec8ce06dc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1MDIzMjUsIm5iZiI6MTcwNjUwMjAyNSwicGF0aCI6Ii82MDE1MDcwMS8zMDAyNzk4OTAtZGVhNTdmZGEtNGM1Ni00YTIwLTk1OTEtMDIyZWM4Y2UwNmRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI5VDA0MjAyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRmNDM2MWUzYmY5Mzc4ZDc3NDYwODU4OGVlNGMxYTM3YjBiNjdjMTFlMDdkNjU2YmMzNDZhNGZkNDE3ODJjZDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0_lWcRLyPrSjkXT-rqK8JerSCzsO7biKXy3VD82E_VQ)
> 
> @s-jse are u using the code from https://github.com/stanford-oval/ovalchat ? is there any specific instructions for wikichat to hook up the front end . thanks .

OVALChat was used in the previous version of the demo. The new version uses https://github.com/Chainlit/chainlit.
But you can still use the old front-end to connect to WikiChat's back-end. Instructions for this are included in OVALChat's README file. You can take a look at the instructions under the section "Run in Development Mode", and use WikiChat's back-end instead of the mock back-end.
