### ISSUE TITLE
"RuntimeError: CUDA error: unknown error" when make index-wiki

### ISSUE THREAD

**Issue by xiaochao00** [stanford-oval/WikiChat#20]
Environment:
python 3.8.10
cuda 11.3
toch 1.13.1
NVIDIA GeForce GTX 950M

Error Info:
Traceback (most recent call last):
  File "/root/anaconda3/envs/wikichat/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/root/anaconda3/envs/wikichat/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/root/WikiChat/./ColBERT/colbert/infra/launcher.py", line 115, in setup_new_process
    return_val = callee(config, *args)
  File "/root/WikiChat/./ColBERT/colbert/indexing/collection_indexer.py", line 33, in encode
    encoder.run(shared_lists)
  File "/root/WikiChat/./ColBERT/colbert/indexing/collection_indexer.py", line 62, in run
    self.setup() # Computes and saves plan for whole collection
  File "/root/WikiChat/./ColBERT/colbert/indexing/collection_indexer.py", line 99, in setup
    avg_doclen_est = self._sample_embeddings(sampled_pids)
  File "/root/WikiChat/./ColBERT/colbert/indexing/collection_indexer.py", line 133, in _sample_embeddings
    local_sample_embs, doclens = self.encoder.encode_passages(local_sample)
  File "/root/WikiChat/./ColBERT/colbert/indexing/collection_encoder.py", line 33, in encode_passages
    embs_, doclens_ = self.checkpoint.docFromText(
  File "/root/WikiChat/./ColBERT/colbert/modeling/checkpoint.py", line 79, in docFromText
    D, mask = torch.cat(D)[reverse_indices], torch.cat(mask)[reverse_indices]
RuntimeError: CUDA error: unknown error

**Comment by s-jse** [comment]
This error is related to [ColBERT](https://github.com/stanford-futuredata/ColBERT/) retrieval system that WikiChat v1.0 used. I think it doesn't support older CUDA versions and GPUs.

We have just released WikiChat v2.0, which has a different retrieval system altogether, including a hosted option you can use via an API call. Please refer to the documentation at https://github.com/stanford-oval/WikiChat?tab=readme-ov-file#configure-an-information-retrieval-source.
